# SPDX-FileCopyrightText: 2026 2023 XWiki CryptPad Team <contact@cryptpad.org> and contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

services:
  nc34:
      build:
        context: .
        dockerfile: Dockerfile.dev
        args:
          NC_VERSION: 34
      ports:
        - 8034:8080
      volumes:
        - nc34-config:/nextcloud/config
        - nc34-data:/nextcloud/data
        - ./:/nextcloud/apps/openincryptpad:ro

  nc33:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        NC_VERSION: 33
    ports:
      - 8033:8080
    volumes:
      - nc33-config:/nextcloud/config
      - nc33-data:/nextcloud/data
      - ./:/nextcloud/apps/openincryptpad:ro

  nc32:
      build:
        context: .
        dockerfile: Dockerfile.dev
        args:
          NC_VERSION: 32
      ports:
        - 8032:8080
      volumes:
        - nc32-config:/nextcloud/config
        - nc32-data:/nextcloud/data
        - ./:/nextcloud/apps/openincryptpad:ro

volumes:
  nc34-config:
  nc34-data:
  nc33-config:
  nc33-data:
  nc32-config:
  nc32-data:
