# SPDX-FileCopyrightText: 2023 XWiki CryptPad Team <contact@cryptpad.org> and contributors
# SPDX-License-Identifier: AGPL-3.0-or-later

FROM ubuntu:24.04
ARG NC_VERSION

RUN --mount=target=/var/lib/apt/lists,type=cache,sharing=locked \
    --mount=target=/var/cache/apt,type=cache,sharing=locked \
    apt update \
    && apt install -y \
       php \
       php-zip \
       php-dom \
       php-xml \
       php-mbstring \
       php-gd \
       php-curl \
       php-sqlite3 \
       wget \
       unzip

RUN wget https://download.nextcloud.com/server/releases/latest-${NC_VERSION}.zip
RUN unzip latest-*.zip
WORKDIR /nextcloud
RUN chmod a+x occ
RUN echo '{"application/x-drawio": "image"}' > mimetypealiases.json
RUN echo '{"drawio": ["application/x-drawio"]}' > mimetypemapping.json
RUN echo 'output_buffering = 0' >> php.ini
COPY start-nc.sh /nextcloud/start-nc.sh
EXPOSE 8080
CMD /nextcloud/start-nc.sh
