services:
  nc32:
      build:
        context: .
        dockerfile: Dockerfile.dev
        args:
          NC_VERSION: 32
      ports:
        - 8032:8080
      volumes:
        - nc32-config:/nextcloud/config
        - nc32-data:/nextcloud/data
        - ./:/nextcloud/apps/openincryptpad:ro

  nc31:
      build:
        context: .
        dockerfile: Dockerfile.dev
        args:
          NC_VERSION: 31
      ports:
        - 8031:8080
      volumes:
        - nc31-config:/nextcloud/config
        - nc31-data:/nextcloud/data
        - ./:/nextcloud/apps/openincryptpad:ro

  nc30:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        NC_VERSION: 30
    ports:
      - 8030:8080
    volumes:
      - nc30-config:/nextcloud/config
      - nc30-data:/nextcloud/data
      - ./:/nextcloud/apps/openincryptpad:ro

volumes:
  nc32-config:
  nc32-data:
  nc31-config:
  nc31-data:
  nc30-config:
  nc30-data:
