FROM ubuntu:24.04 AS nextcloud-git
RUN --mount=target=/var/lib/apt/lists,type=cache,sharing=locked \
    --mount=target=/var/cache/apt,type=cache,sharing=locked \
    apt update \
    && apt install -y \
       git
RUN git clone https://github.com/nextcloud/server.git nextcloud



FROM ubuntu:24.04
ARG NC_VERSION

RUN --mount=target=/var/lib/apt/lists,type=cache,sharing=locked \
    --mount=target=/var/cache/apt,type=cache,sharing=locked \
    apt update \
    && apt install -y \
       git \
       php \
       php-zip \
       php-dom \
       php-xml \
       php-mbstring \
       php-gd \
       php-curl \
       php-sqlite3

COPY --from=nextcloud-git /nextcloud /nextcloud
WORKDIR /nextcloud
RUN git fetch && git checkout ${NC_VERSION}
RUN git submodule update --init
RUN echo '{"application/x-drawio": "image"}' > mimetypealiases.json
RUN echo '{"drawio": ["application/x-drawio"]}' > mimetypemapping.json
EXPOSE 8080
CMD cp mimetype*.json config \
    && php -S 0.0.0.0:8080
